name: omegapoint
recipe: laravel
config:
  webroot: public
  via: nginx
  php: '8.4'
  composer_version: 2-latest
  composer:
    'deployer/deployer' : '~7'
services:
  appserver:
    overrides:
      environment:
        - SSH_AUTH_SOCK=/ssh-agent
      volumes:
        - ${SSH_AUTH_SOCK}:/ssh-agent
  database:
    scanner: false
    healthcheck: false
  node:
    type: node:20
    scanner: false
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
tooling:
  rector:
    service: appserver
    cmd:
      - "vendor/bin/rector"
  node:
    service: node
  npm:
    service: node
  dep:
    service: appserver
    desription: run deployer commands
    cmd:
      - "dep"
  reset:
    service: appserver
    desription: erase DB and re-seed
    cmd:
      - "php artisan db:wipe"
      - "php artisan migrate"
      - "php artisan db:seed"
  csfixer:
    service: appserver
    description: Run PHP Coding Standards Fixer.
    cmd: /app/vendor/bin/php-cs-fixer --config=cs-fixer.php
    env:
      PHP_CS_FIXER_IGNORE_ENV: 1
proxy:
  appserver_nginx:
    - omegapoint.lndo.site
    - admin.omegapoint.lndo.site
    - news.omegapoint.lndo.site
  node:
    - node.omegapoint.lndo.site:80
